# Generated by Django 4.1.6 on 2023-06-28 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='stakeholders/img/Atividades')),
                ('custo', models.TextField(blank=True)),
                ('pessoa_de_contato', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.TextField()),
                ('morada', models.TextField()),
                ('codigo_postal', models.TextField()),
                ('contacto_telefonico', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes_do_meio', models.TextField(blank=True)),
                ('data_nascimento', models.DateField(blank=True)),
                ('nif', models.TextField(blank=True)),
                ('morada', models.TextField(blank=True)),
                ('codigo_postal', models.TextField(blank=True)),
                ('freguesia', models.TextField(blank=True)),
                ('concelho', models.TextField(blank=True)),
                ('distrito', models.TextField(blank=True)),
                ('contacto', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.atividade')),
                ('local', models.TextField(blank=True)),
                ('gps', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('objetivo', models.TextField(blank=True)),
                ('publico_alvo', models.TextField(blank=True)),
                ('data_inicio_inscricao', models.DateField()),
                ('data_limite_inscricao', models.DateField()),
                ('vagas', models.TextField(blank=True)),
                ('tipoevento', models.CharField(choices=[('C', 'Curso'), ('F', 'Formacao'), ('CO', 'Congresso'), ('PA', 'Palestra'), ('SE', 'Seminario'), ('CN', 'Concurso')], max_length=2)),
            ],
            bases=('stakeholders.atividade',),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.atividade')),
                ('detalhes', models.TextField(blank=True)),
            ],
            bases=('stakeholders.atividade',),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('morada', models.TextField(blank=True)),
                ('codigo_postal', models.TextField(blank=True)),
                ('contacto_telefonico', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pessoa_de_contato', models.TextField(blank=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='PessoasDeContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_telefonico', models.TextField(blank=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.entidade'),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.evento')),
                ('tipo', models.CharField(choices=[('PG', 'PosGraduacao'), ('LI', 'Licenciatura'), ('ME', 'Mestrado'), ('DO', 'Doutoramento')], max_length=2)),
                ('tipo_de_aluno', models.CharField(choices=[('IJ', 'ImpulsoJovem'), ('IA', 'ImpulsoAdulto'), ('AM', 'Ambos')], max_length=2)),
                ('ects', models.TextField(blank=True)),
            ],
            bases=('stakeholders.evento',),
        ),
        migrations.CreateModel(
            name='PreInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pre_inscricao', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.participante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Portefolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField()),
                ('data_de_fim', models.DateField()),
                ('imagens_de_referencia', models.ImageField(blank=True, upload_to='stakeholders/img/Servicos')),
                ('detalhes', models.TextField(blank=True)),
                ('publico', models.BooleanField(blank=True)),
                ('data_de_requisicao', models.DateField()),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.servico')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='atividades',
            field=models.ManyToManyField(through='stakeholders.PreInscricao', to='stakeholders.evento'),
        ),
    ]
