# Generated by Django 4.2.2 on 2023-06-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='stakeholders/img/Atividades')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('area', models.CharField(choices=[('Saúde', 'Saúde'), ('Tecnologia', 'Tecnologia'), ('Agricultura', 'Agricultura'), ('Educação', 'Educação'), ('Matemática', 'Matemática'), ('Outras', 'Outras')], default='Tecnologia', max_length=20)),
                ('local', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('custos', models.TextField(blank=True)),
                ('publico_alvo', models.TextField(blank=True)),
                ('contacto', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.TextField(blank=True)),
                ('nif', models.TextField(blank=True)),
                ('morada', models.TextField(blank=True)),
                ('codigo_postal', models.TextField(blank=True)),
                ('freguesia', models.TextField(blank=True)),
                ('concelho', models.TextField(blank=True)),
                ('distrito', models.TextField(blank=True)),
                ('contacto', models.TextField(blank=True)),
                ('atividades', models.ManyToManyField(through='stakeholders.Inscricao', to='stakeholders.atividade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('morada', models.TextField()),
                ('contacto', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeFormativa',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.atividade')),
                ('data_limite_inscricao', models.DateField()),
                ('responsavel', models.TextField()),
                ('tipodeatividade', models.CharField(choices=[('C', 'Curso'), ('F', 'Formacao')], default='C', max_length=2)),
                ('certificacao', models.TextField(blank=True)),
                ('programa', models.TextField(blank=True)),
                ('duracao', models.TextField(blank=True)),
                ('vagas', models.TextField(blank=True)),
                ('edicao', models.TextField(blank=True)),
                ('requisitos', models.TextField(blank=True)),
                ('horario', models.TextField(blank=True)),
                ('fases', models.TextField(blank=True)),
                ('regime', models.TextField(blank=True)),
            ],
            bases=('stakeholders.atividade',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.atividade')),
                ('tipodeevento', models.CharField(choices=[('CO', 'Congresso'), ('PA', 'Palestra'), ('SE', 'Seminario'), ('CN', 'Concurso')], default='CO', max_length=2)),
                ('data_limite_inscricao', models.DateField()),
                ('programa', models.TextField(blank=True)),
                ('duracao', models.TextField(blank=True)),
                ('vagas', models.TextField(blank=True)),
                ('horario', models.TextField(blank=True)),
                ('agenda', models.TextField(blank=True)),
                ('alojamento', models.TextField(blank=True)),
                ('local_alojamento', models.TextField(blank=True)),
                ('orador', models.TextField(blank=True)),
                ('moderador', models.TextField(blank=True)),
                ('data_submissao_resumos', models.DateField(blank=True)),
                ('data_notificacao_resumos', models.DateField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('parcerias', models.TextField(blank=True)),
                ('numero_elementos_equipa', models.IntegerField(blank=True)),
            ],
            bases=('stakeholders.atividade',),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.profile')),
                ('genero', models.CharField(choices=[('E', 'Escolha Uma'), ('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='E', max_length=1)),
                ('nacionalidade', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('formacao_academica', models.CharField(choices=[('E', 'Escolha Uma'), ('4', '4º ano'), ('9', '9º ano'), ('12', '12º ano'), ('L', 'Licenciatura'), ('M', 'Mestrado'), ('D', 'Doutoramento')], default='E', max_length=2)),
                ('atividade_profissional', models.CharField(choices=[('E', 'Escolha Uma'), ('ES', 'Estudante - Secundário'), ('EL', 'Estudante - Licenciatura'), ('EO', 'Estudante - Outra'), ('TP', 'Trabalhador por conta própria'), ('TO', 'Trabalhador por conta de outrem'), ('DE', 'Desempregado'), ('O', 'Outra')], default='E', max_length=2)),
            ],
            bases=('stakeholders.profile',),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.atividade')),
            ],
            bases=('stakeholders.atividade',),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.profile'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade_organica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.unidadeorganica'),
        ),
    ]
