# Generated by Django 4.2.2 on 2023-06-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='tipo',
            field=models.CharField(choices=[('PG', 'PosGraduacao'), ('LI', 'Licenciatura'), ('ME', 'Mestrado'), ('DO', 'Doutoramento'), ('OU', 'Outros')], max_length=2),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.TextField(blank=True)),
                ('morada', models.TextField(blank=True)),
                ('codigo_postal', models.TextField(blank=True)),
                ('contacto_telefonico', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descricao', models.TextField(blank=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.entidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
